name: Build and release PROTA Tool

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Install NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore PROTATool/PROTATool.csproj -SolutionDirectory PROTATool

      - name: Validate NuGet Packages
        run: dir PROTATool/packages

      - name: Create Output Directory
        run: mkdir -p BuildOutput/Release

      - name: Build the project
        run: msbuild PROTATool/PROTATool.csproj /p:Configuration=Release /p:OutDir=BuildOutput\Release\

      - name: Debug Build Output Directory
        run: |
          echo "Checking contents of BuildOutput/Release:"
          dir BuildOutput/Release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PROTATool
          path: |
            BuildOutput/Release/*.exe
            BuildOutput/Release/*.dll
          if-no-files-found: warn

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: PROTATool

      - name: Debug Download Artifacts
        run: |
          echo "Downloaded artifacts:"
          dir .

      - name: Recreate Directory Structure
        run: |
          echo "Recreating BuildOutput directory..."
          mkdir -p BuildOutput/Release
          move *.exe BuildOutput/Release/
          move *.dll BuildOutput/Release/

      - name: Debug Downloaded Artifacts
        run: |
          echo "Downloaded artifacts in BuildOutput/Release:"
          dir BuildOutput/Release

      - name: Create ZIP File
        run: |
          mkdir release
          powershell Compress-Archive -Path "BuildOutput/Release/*" -DestinationPath "release/PROTATool-v${{ github.run_number }}.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: PROTA Tool v${{ github.run_number }}
          body: |
            Automated release for PROTATool.
            Includes the latest .exe and .dll files.
          draft: false
          prerelease: false
          files: release/PROTATool-v${{ github.run_number }}.zip
